title: Refucomm
email: sharonsilvey1@gmail.com
description: >
  Vital information and communication for displaced refugees.
twitter_username: silvey_sharon
facebook: RefuComm-communication-and-information-for-refugees-145594569125687
github_username:  refucomm
include: ['_pages', '_locations']